### ISSUE TITLE
写文件

### ISSUE THREAD

**Issue by xadlovezy** [wuxudong/flashbot#3]
大神，如何要目标机里创建文件，并写入内容呢，我知道用touch,echo但是不是知道怎么用代码实现。求解答，感谢啊

**Comment by wuxudong** [comment]
用一个 偷懒的办法， 工程里不是有 PUSH 么， 你可以在本地创建一个文件， 写好内容， 然后 push 到 目标机里。

**Comment by xadlovezy** [comment]
我来试试，好思路啊，感谢啊
